# fly.toml app configuration file generated for cohzy-brain-v2 on 2024-10-14T05:19:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cohzy-brain-v2'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.http_checks]]
  interval = "10s"
  grace_period = "10s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[[services.machine_checks]]  # Updated section for machine checks
  image = "curlimages/curl"  # Docker image to use for the check
  entrypoint = ["/bin/sh", "-c"]  # Entry point for the test
  command = ["curl -f -s -o /dev/null http://[$FLY_TEST_MACHINE_IP]/health"]  # Command to check for a 200 status
  kill_signal = "SIGKILL"  # Signal to send if the test runs too long
  kill_timeout = "5s"  # Time to wait before sending the kill signal
